# Customize the codemagic.yaml file according to your project and commit it to the root of your repository
# Check out https://docs.codemagic.io/getting-started/yaml/ for more information
# You can also download your configuration from Worklow Editor to get started

workflows:
  main-workflow:
    name: Main Workflow
    scripts:
      - name: Build ios
        script: flutter build ios --debug
      - name: Build android
        script: flutter build apk --debug
    publishing:
      email:
        recipients:
          - Encrypted(Z0FBQUFBQmdYRGxyTGVtSnVLbEZ2ckJCb3Q2YjFkcnpjWWo0V1o5ajdia1hCMHMtanZpM3JZMUg5ZXlHOHlqcnlvOHNhaUJaVG01QWo2N2NENFh3dS1Vd2VsaTJrOFNydHRnSkEyRDM1Y1QzRmtNWlZiYmh4TEE9)

  example-workflow:
    name: Example Workflow
    scripts:
      - name: Step name
        script: echo "Hello Codemagician!"
    publishing:
      email:
        recipients:
          - Encrypted(Z0FBQUFBQmdYRGxyTGVtSnVLbEZ2ckJCb3Q2YjFkcnpjWWo0V1o5ajdia1hCMHMtanZpM3JZMUg5ZXlHOHlqcnlvOHNhaUJaVG01QWo2N2NENFh3dS1Vd2VsaTJrOFNydHRnSkEyRDM1Y1QzRmtNWlZiYmh4TEE9)